serverAddr = '123.207.31.122'
serverPort = 7000

[[proxies]]
name = 'web'
type = 'http'
localPort = 3000
subdomain = 'test'

[[proxies]]
name = 'ws'
type = 'tcp'
protocol = 'wss'
localPort = 3000
subdomain = 'test'
